plugins:
        #https://github.com/babel/eslint-plugin-babel
        - babel
env:
  es6: true
  node: true
parser: babel-eslint
extends:
  - airbnb-base  
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
        no-console: 0
}
